export class Constants {
    /**
     * Titles of lists generated by sharepoint. Ignore these lists
     
    public static readonly listsToIgnore = [
        "Form Templates",
        "Resources",
        "Reusable Content",
        "Site Assets",
        "Site Collection Documents",
        "Site Collection Images",
        "Site Pages" ,
        "Style Library",
        "Workflow Tasks",
        "Content and Structure Reports"
    ];*/
}